version: 2

models:
  - name: stg_saas_dbt__customer_cases
    description: >
      Cleaned and standardized staging model for customer support cases.
      Prepares data for downstream modeling by applying column renaming,
      value trimming, type enforcement, and controlled vocabularies.

    columns:
      - name: case_id
        description: Unique identifier for each customer support case
        tests:
          - unique
          - not_null

      - name: created_at
        description: Timestamp when the case was created (converted to TIMESTAMP with timezone)
        tests:
          - not_null

      - name: customer_id
        description: Foreign key to the customer dimension table
        tests:
          - not_null

      - name: channel
        description: Contact method used by the customer (standardized lowercase)
        tests:
          - accepted_values:
              values: ['email', 'phone']
              config:
                severity: warn

      - name: reason
        description: Customer-reported reason for the case (standardized lowercase)
        tests:
          - accepted_values:
              values: ['signup', 'support', 'cancel']
              config:
                severity: warn

  - name: stg_saas_dbt__customer_info
    description: >
      Cleaned and standardized staging model for customer info.
      Prepares data for downstream modeling by applying column renaming,
      value trimming, type enforcement, and controlled vocabularies.
    columns:
      - name: customer_id
        description: Unique identifier for customer_cases
        tests:
          - unique
          - not_null 
      - name: age 
        description: age of the customer (int data type)
        tests: 
          - not_null
          - dbt_utils.expression_is_true:
              expression: "age between 10 and 100"
      - name: gender 
        description: Gender of the customer
        tests:
          - not_null
          - accepted_values:
              values: ['male', 'female', 'other', 'prefer not to say']
              config:
                severity: warn

  - name: stg_saas_dbt__customer_product
    description: >
      Cleaned and standardized staging model for customer and product.
      Prepares data for downstream modeling by applying column renaming,
      value trimming, type enforcement, and controlled vocabularies.
    columns:
      - name: customer_id
        description: Foreign key referencing unique customer id from customer info
        tests:
          - not_null
          - unique 
      - name: product_id
        description: id of the product refernecing product info table.
        tests:
          - not_null
      - name: signup_time
        description: timestamp of customer signup
        tests: 
          - not_null
      - name: cancel_time 
        description: timstamp of customer cancellation.
      - name: is_active 
        description: boolean flag indicating whether the customer is currently active or not
        tests:
          - not_null

  - name: stg_saas_dbt__product_info
    description: >
      Cleaned and standardized staging model for product info.
      Prepares data for downstream modeling by applying column renaming,
      value trimming, type enforcement, and controlled vocabularies. 

    columns:
      - name: product_id 
        description: unique identifier for a product
        tests:
          - not_null 
          - unique 
      - name: billing_type
        description: type of subscription plam
        tests: 
          - not_null
          - accepted_values:
              values: ['annual', 'monthly']
              config:
                severity: warn
      - name: price 
        description: price listed for the product
        tests:
          - not_null
      - name: billing_cycle 
        description: billing cycle in integer value representing months
        tests:
          - not_null 
      

        

